#Set the root logging level
logging.level.root=INFO

#Set the logging level for a specific package
logging.level.org.gathadi.cardatabase=DEBUG

#Set the logging level for a specific class
logging.level.org.gathadi.cardatabase.CardatabaseApplication=TRACE

#Setting the server port
#server.port=9090

#Setting the database connection
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=ajaygathadi
#spring.datasource.password=ajaygathadis

spring.datasource.url=jdbc:postgresql://localhost:5432/cardatabase
spring.datasource.username=agathadi
spring.datasource.password=Cardatabase@8955
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true

#Endpoint of the service
spring.data.rest.basePath=/api

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

#This allows us to log the SQL statements to the console.
spring.jpa.show-sql=true

spring.h2.console.path=/h2-console
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.config-url=/v1/api-docs/swagger-config
